version: "3"

services:
  api:
    image: 'myth-api:latest'
    env_file:
        - .env
    ports:
      - '${APP_PORT-8080}:80'
    volumes:
      - './:/code'
      - './requirements.txt:/code/requirements.txt'
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1001}
    networks:
      - myths

  db:
    image: postgres:12
    ports:
      - '${POSTGRES_FORWARD_PORT-5432}:5432'
    networks:
      - myths
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - myths
    ports:
      - '${PG_ADMIN_PORT-8081}:5050'
    depends_on:
      - db
    env_file:
      - .env

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - myths

networks:
    myths:
        driver: bridge

volumes:
  app-db-data: