version: "3"

services:
  api:
    image: 'myth-api:latest'
    env_file:
        - app/.env
    ports:
      - '${APP_PORT-8080}:80'
    volumes:
      - './app:/code/app'
    build:
      context: .
      dockerfile: Dockerfile